kind: Deployment
apiVersion: apps/v1
metadata:
  name: trader-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trader
  template:
    metadata:
      name: trader
      labels:
        app: trader
    spec:
      restartPolicy: Always
      containers:
        - name: trader
          image: binance_trader_services:latest
          command: ["python", "-m", "trader.trader_v1", "run"]
          imagePullPolicy: "Never"
          env:
            - name: POSTGRES_HOST
              value: database.dev.svc.cluster.local         
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: LEVERAGE
              value: {{LEVERAGE}}
            - name: EXP_NAME
              value: {{EXP_NAME}}
            - name: REPORT_PREFIX
              value: {{REPORT_PREFIX}}
            - name: REPORT_BASE_CURRENCY
              value: {{REPORT_BASE_CURRENCY}}
            - name: REPORT_ID
              value: {{REPORT_ID}}
            - name: EXCHANGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: market-secret
                  key: api_key
            - name: EXCHANGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: market-secret
                  key: secret_key
            - name: TEST_MODE
              valueFrom:
                secretKeyRef:
                  name: market-secret
                  key: test_mode
          volumeMounts:
            - name: svc-codes
              mountPath: "/app/src"
            - name: dev-codes
              mountPath: "/app/dev/src"
            - name: dev-exps
              mountPath: "/app/dev/experiments"
            - name: svc-trader-artifacts
              mountPath: "/app/storage/trader"
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 850m
              memory: 1000Mi
      volumes:
        - name: svc-codes
          hostPath:
            path: {{PWD}}/src
        - name: dev-codes
          hostPath:
            path: {{PARENT_PWD}}/develop/src
        - name: dev-exps
          hostPath:
            path: {{PARENT_PWD}}/develop/storage/experiments
        - name: svc-trader-artifacts
          hostPath:
            path: {{PWD}}/storage/trader